version: '3'

services:
  db:
    image: postgres
    container_name: pizza-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: pizza
    networks:
      - pizza

  backend:
    build: backend
    command: npm start
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: pizza-db
      DB_PORT: '5432'
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: psql
      DB_NAME: pizza
    networks:
      - pizza
    labels:
      - traefik.enable=true
      - traefik.http.services.pizza-backend.loadbalancer.server.port=3000
      - traefik.http.routers.pizza-backend.entrypoints=https
      - traefik.http.routers.pizza-backend.rule=Host(`api.pizza.ew-production.ru`)
      - traefik.http.routers.pizza-backend.tls=true
      - traefik.http.routers.pizza-backend.tls.certresolver=le
      - traefik.docker.network=pizza

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.pizza.ew-production.ru
    networks:
      - pizza
    labels:
      - traefik.enable=true
      - traefik.http.services.pizza-frontend.loadbalancer.server.port=80
      - traefik.http.routers.pizza-frontend.entrypoints=https
      - traefik.http.routers.pizza-frontend.rule=Host(`pizza.ew-production.ru`)
      - traefik.http.routers.pizza-frontend.tls=true
      - traefik.http.routers.pizza-frontend.tls.certresolver=le
      - traefik.docker.network=pizza

networks:
  pizza:
    external: true
