FROM node:20

WORKDIR /app

COPY package.json .npmrc ./
RUN npm cache clean --force && rm -f package-lock.json && npm install
COPY . .

EXPOSE 5001

CMD ["sh", "-c", "mkdir -p /app/node_modules/@pizza && cp -r /packages/common /app/node_modules/@pizza/common && npm run dev -- --host 0.0.0.0"]
