FROM node:20

WORKDIR /app

# Copy package files
COPY auth/package.json ./
COPY auth/.npmrc ./

# Install dependencies
RUN npm cache clean --force && rm -f package-lock.json && npm install

# Copy @pizza packages
COPY packages/shared /app/node_modules/@pizza/shared

# Copy source files
COPY auth/ .

EXPOSE 5001

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
