FROM node:20

WORKDIR /app

COPY order/package.json ./

RUN npm install

COPY packages/shared/src /app/node_modules/@pizza/shared

COPY order/ .

EXPOSE 5005

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
